services:
  app:
    image: experimental-service:latest
    ports:
      - "8080"
    environment:
      - DB_DSN=postgresql://app_user:app_password@db:5432/app_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    
  migrations:
    image: experimental-service-migrations:latest
    entrypoint: 'sh -c "trap : TERM INT; sleep 604800; wait"'
    environment:
      - DB_DSN=postgresql://app_user:app_password@db:5432/app_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:11.2-alpine
    environment:
      - TZ=Asia/Novosibirsk
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
    ports:
      - "5432"
    healthcheck:
      test: "pg_isready -U app_db"
      interval: 10s
      timeout: 5s
      retries: 100

  kafka:
    image: bitnami/kafka:3.2.3
    ports:
      - "9092"
      - "9094"
    environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_CFG_MESSAGE_MAX_BYTES=1048588 # дефолтное значение, проблема описана тут https://github.com/bitnami/containers/issues/55274, убрать при обновлении
        - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
        - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "kafka-topics.sh --bootstrap-server kafka:9092 --list | grep test"
      interval: 20s
      timeout: 10s
      retries: 6
