services:
  e2e:
    image: experimental-service-e2e:latest
    entrypoint: 'sh -c "trap : TERM INT; sleep 604800; wait"'
    volumes:
      - .:/project
      - ./tests/e2e:/e2e
    working_dir: /e2e
    environment:
      - DOCKER_HOST=tcp://dockersock:2375
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - NON_STOP_CONTAINERS=dockersock,e2e
      - HOST_PROJECT_ROOT_DIRECTORY=${HOST_PROJECT_ROOT_DIRECTORY}

  dockersock:
    image: docker-hub.2gis.ru/ugc/dockersock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "wget -q -O - http://localhost:2375/v1.40/version || exit 1"
      interval: 5s
      timeout: 10s
      retries: 100
